# Sample Email Responses (Images)

This file displays the visual screenshots of the automatic replies generated by the AI agent.

---

### 📋 Sample 1: Registration Query
![Sample 1](sample%201.jpeg)

---

### 📦 Sample 2: Sponsorship Query
![Sample 2](sample%202.jpeg)

---

### 🛠️ Sample 3: Support Query
![Sample 3](sample%203.jpeg)

---

### ❓ Sample 4: Ambiguous Email
![Sample 4](sample%204.jpeg)

---

### 🗑️ Sample 5: Spam Detected
![Sample 5](sample%205.jpeg)
